/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GetAccessRouteImport } from './routes/get-access'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SemesterSemRouteImport } from './routes/semester.$sem'
import { Route as PdfPdfIdRouteImport } from './routes/pdf.$pdfId'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as SubjectSemSubjectRouteImport } from './routes/subject.$sem.$subject'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAccessRoute = GetAccessRouteImport.update({
  id: '/get-access',
  path: '/get-access',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterSemRoute = SemesterSemRouteImport.update({
  id: '/semester/$sem',
  path: '/semester/$sem',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfPdfIdRoute = PdfPdfIdRouteImport.update({
  id: '/pdf/$pdfId',
  path: '/pdf/$pdfId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/$bookId',
  path: '/$bookId',
  getParentRoute: () => BooksRoute,
} as any)
const SubjectSemSubjectRoute = SubjectSemSubjectRouteImport.update({
  id: '/subject/$sem/$subject',
  path: '/subject/$sem/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/books': typeof BooksRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/get-access': typeof GetAccessRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/pdf/$pdfId': typeof PdfPdfIdRoute
  '/semester/$sem': typeof SemesterSemRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/subject/$sem/$subject': typeof SubjectSemSubjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/books': typeof BooksRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/get-access': typeof GetAccessRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/pdf/$pdfId': typeof PdfPdfIdRoute
  '/semester/$sem': typeof SemesterSemRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/subject/$sem/$subject': typeof SubjectSemSubjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/books': typeof BooksRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/get-access': typeof GetAccessRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/pdf/$pdfId': typeof PdfPdfIdRoute
  '/semester/$sem': typeof SemesterSemRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/subject/$sem/$subject': typeof SubjectSemSubjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/books'
    | '/feedback'
    | '/get-access'
    | '/library'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/books/$bookId'
    | '/pdf/$pdfId'
    | '/semester/$sem'
    | '/api/public/bootstrap-admin'
    | '/subject/$sem/$subject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/books'
    | '/feedback'
    | '/get-access'
    | '/library'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/books/$bookId'
    | '/pdf/$pdfId'
    | '/semester/$sem'
    | '/api/public/bootstrap-admin'
    | '/subject/$sem/$subject'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/books'
    | '/feedback'
    | '/get-access'
    | '/library'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/books/$bookId'
    | '/pdf/$pdfId'
    | '/semester/$sem'
    | '/api/public/bootstrap-admin'
    | '/subject/$sem/$subject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BooksRoute: typeof BooksRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  GetAccessRoute: typeof GetAccessRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  PdfPdfIdRoute: typeof PdfPdfIdRoute
  SemesterSemRoute: typeof SemesterSemRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  SubjectSemSubjectRoute: typeof SubjectSemSubjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-access': {
      id: '/get-access'
      path: '/get-access'
      fullPath: '/get-access'
      preLoaderRoute: typeof GetAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester/$sem': {
      id: '/semester/$sem'
      path: '/semester/$sem'
      fullPath: '/semester/$sem'
      preLoaderRoute: typeof SemesterSemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf/$pdfId': {
      id: '/pdf/$pdfId'
      path: '/pdf/$pdfId'
      fullPath: '/pdf/$pdfId'
      preLoaderRoute: typeof PdfPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof BooksRoute
    }
    '/subject/$sem/$subject': {
      id: '/subject/$sem/$subject'
      path: '/subject/$sem/$subject'
      fullPath: '/subject/$sem/$subject'
      preLoaderRoute: typeof SubjectSemSubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BooksRouteChildren {
  BooksBookIdRoute: typeof BooksBookIdRoute
}

const BooksRouteChildren: BooksRouteChildren = {
  BooksBookIdRoute: BooksBookIdRoute,
}

const BooksRouteWithChildren = BooksRoute._addFileChildren(BooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  BooksRoute: BooksRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  GetAccessRoute: GetAccessRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  PdfPdfIdRoute: PdfPdfIdRoute,
  SemesterSemRoute: SemesterSemRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  SubjectSemSubjectRoute: SubjectSemSubjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
